### ISSUE TITLE
Sim freezes after 1 targeted completed and attempting to collapse expanded container

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/build-a-fraction#6]
@phet-steele would be proud of me for this find...

This appears to happen on any Mixed Numbers "Shapes" challenges (numbers as targets, shapes to construct answers). Seen in https://phet-dev.colorado.edu/html/build-a-fraction/1.0.0-dev.12/phet/build-a-fraction_en_phet.html and reproduced on both Chrome and FF Win 7. Guessing it is a ubiquitous issue.

Simplest reproducible case:
1. Go to a simple level (ie level 2)
2. Complete one target (this freeze only occurs if a target has been completed)
3. Full expand a container in the play area
4. Put one piece in the right most container
5. Press the red collapse "remove container" button
6. The sim will freeze and become unusable

Saw this in the console:

> Uncaught TypeError: this.returnPieceListener is not a function
>     at i.value (build-a-fraction_en_phet.html:980)
>     at e.value (build-a-fraction_en_phet.html:980)
>     at e.fire (build-a-fraction_en_phet.html:980)
>     at Array.a (build-a-fraction_en_phet.html:980)
>     at e.value (build-a-fraction_en_phet.html:980)
>     at e._notifyListeners (build-a-fraction_en_phet.html:980)
>     at e.setValueAndNotifyListeners (build-a-fraction_en_phet.html:980)
>     at e.set (build-a-fraction_en_phet.html:980)
>     at e.value (build-a-fraction_en_phet.html:980)
>     at e._notifyListeners (build-a-fraction_en_phet.html:980)

Picture included for reference of frozen condition and steps above

![baf](https://user-images.githubusercontent.com/4051174/50197931-a259ec00-0306-11e9-8b9f-2f5ca386f81e.PNG)

**Comment by ariel-phet** [comment]
@jonathanolson considering this bug high priority since it freezes the sim

**Comment by jonathanolson** [comment]
This should have been resolved by the commit for https://github.com/phetsims/fractions-common/issues/36, can you verify?

**Comment by ariel-phet** [comment]
Checked in master. Appears fixed. Closing

**Comment by amanda-phet** [comment]
@arouinfar was using dev.10 because I sent a link before dev.11 was published. So @KatieWoe should confirm that it's still present.

**Comment by arouinfar** [comment]
Self-assigning to review the interview screen captures. I'll report back soon. If I figure out a procedure that breaks dev.10, I'll verify it also breaks dev.11.

**Comment by phet-steele** [comment]
The bug happens easily in dev.10 of FMN using the above steps. Moving on to dev.11 the steps no longer break the sim. I believe we are fine. The commit to fix this (https://github.com/phetsims/fractions-common/commit/2dda2b9d1c6d475a6e1a7a7ca0d5a33fa8a371a0) was made in-between dev.10 and dev.11, so this is all expected.

**Comment by arouinfar** [comment]
I saw 7-8 instances of this bug in dev.10. Reviewing the interview screen capture confirms that it was always encountered in the way @ariel-phet originally described, though step (3) was optional. The bug occurred even if the container wasn't fully expanded.
